# Especificacion de la version de API a usar.
apiVersion: apps/v1
# Tipo de recurso.
kind: Deployment
metadata:
  # Nombre del recurso deployment.
  name: nodejs
  # Namespace donde se trabajara.
  namespace: sopes1
# Especificaciones del deployment.
spec:
  # De esta forma sabemos que Pods pertenecen al deployment
  selector:
    matchLabels:
      app: deployment-nodejs
  # Cantidad de pods y sus replicas a crear.
  replicas: 1
  # Plantilla que utilizara el deployment para crear los Pods
  template:
    # Vinculamos el Pod con el deployment especificado en la linea 15.
    metadata:
      labels:
        app: deployment-nodejs
    # Especificaciones del Pod.
    spec:
      # Contenedores que tendra el Pod.
      containers:
        # Nombre del contenedor.
        - name: server-nodejs
          # Imagen a descargar desde DockerHub
          image: <user-dockerhub>/api-nodejs:v3
          # Puerto donde se expondra nuestro contenedor
          ports:
            - containerPort: 4000

---
# Especificacion de la version de API a usar.
apiVersion: v1
# Tipo de recurso.
kind: Service
# Nombre del recurso.
metadata: 
  name: service-nodejs
  # Namespace donde se trabajara.
  namespace: sopes1
spec:
  # Tipo de Service que crea una IP externa para exponer el servicio.
  type: LoadBalancer
  # Selector que asocia este Service con los Pods etiquetados.
  selector:
    app: deployment-nodejs
  ports:
    - name: nodejs-port  # Nombre simbólico del puerto (opcional pero útil).
      protocol: TCP
      # Puerto en el que se expondrá el servicio dentro del clúster (y externamente si es LoadBalancer).
      port: 4000
      # Puerto interno del contenedor al que se redirigirá el tráfico.
      targetPort: 4000
